import { insertContactRequest } from "@/app/lib/filmQueries";
import Sidebar from "@/app/components/Sidebar";
export const metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};
const Contact = async () => {
  return (
    <main>
      <div className='banner'>
        <h2>Contact Us</h2>
      </div>
      <section className='twoColumn'>
        <div>
          {/* <form onSubmit={handleSubmit}> */}
          <form>
            <div>
              <label htmlFor='firstname'>First name</label>
              <input
                type='text'
                name='firstname'
                id='firstname'
                placeholder='Your First Name'
              />
            </div>
            <div>
              <label htmlFor='lastname'>Last Name</label>
              <input
                type='text'
                name='lastname'
                id='lastname'
                placeholder='Your Last Name'
              />
            </div>
            <div>
              <label htmlFor='email'>Email</label>
              <input type='email' name='email' id='email' required />
            </div>
            <div>
              <label htmlFor='tel'>Contact Telephone</label>
              <input type='tel' name='tel' id='tel' required />
            </div>
            <div>
              <label htmlFor='marketing'>How did you hear about us?</label>
              <select name='marketing' id='marketing'>
                <option value='Web'>Web</option>
                <option value='Friend'>Friend</option>
                <option value='Other'>Other</option>
              </select>
            </div>
            <div>
              <input type='submit' value='Send' className='sendButton' />
            </div>
          </form>
        </div>
        <Sidebar />
      </section>
    </main>
  );
};
export default Contact;
