import styles from "./cms.module.css";
import Link from "next/link";
import { fetchFilms } from "@/app/lib/filmQueries";
export const metadata = {
  title: "Catalogue - My Film Listing",
  description: "Generated by create next app",
};
const Cms = async () => {
  const films = await fetchFilms();

  return (
    <main>
      <div className='banner'>
        <h2>CMS</h2>
      </div>
      <section className='twoColumn'>
        <div className='listing'>
          <div>
            <Link href={"cms/add"}>Add Film</Link>
          </div>
          <table className={styles.table}>
            <thead>
              <tr>
                <th>Film</th>
                <th>Edit</th>
                <th>Delete</th>
              </tr>
            </thead>
            <tbody>
              {/* Loop over the films and display them here: */}
              {films.map((film, index) => (
                <tr key={index}>
                  <td>
                    <Link href={`/catalogue/${film.film_id}`}>
                      {film.film_title}
                    </Link>
                  </td>
                  <td>
                    <Link href={`cms/edit/${film.film_id}`}>Edit</Link>
                  </td>
                  <td>
                    <Link href={`cms/delete/${film.film_id}`}>Delete</Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </main>
  );
};
export default Cms;
