import Link from "next/link";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "My Film Listing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link rel='stylesheet' href='/css/mobile.css' />
        <link
          rel='stylesheet'
          href='/css/desktop.css'
          media='only screen and (min-width : 720px)'
        />
      </head>
      <body>
        <Navbar />
        <div className='mainContainer'>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
