import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { headers } from "next/headers";

export const metadata = {
  title: "My Film Listing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const sessionHeader = headers().get("x-session-valid");
  // Check session status from headers
  const isAuthenticated = sessionHeader === "true";
  return (
    <html lang='en'>
      <head>
        <link rel='stylesheet' href='/css/mobile.css' />
        <link
          rel='stylesheet'
          href='/css/desktop.css'
          media='only screen and (min-width : 720px)'
        />
      </head>
      <body>
        <Navbar isAuthenticated={isAuthenticated} />
        <div className='mainContainer'>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
