import Link from "next/link";
import { fetchFilms } from "@/app/lib/db";
export const metadata = {
  title: "Catalogue - My Film Listing",
  description: "Generated by create next app",
};
const Catalogue = async () => {
  const films = await fetchFilms();

  console.dir(films);

  return (
    <main>
      <div className='banner'>
        <h2>Catalogue</h2>
      </div>
      <section className='twoColumn'>
        <div className='listing'>
          <table>
            <thead>
              <tr>
                <th>Film</th>
                <th>Certificate</th>
                <th>Price</th>
              </tr>
            </thead>
            <tbody>
              {/* Loop over the films and display them here: */}
              {films.map((film, index) => (
                <tr key={index}>
                  <td data-cell='Title' role='cell'>
                    <Link href={`/catalogue/${film.film_id}`}>
                      {film.film_title}
                    </Link>
                  </td>
                  <td data-cell='Certificate' role='cell'>
                    {film.film_certificate}
                  </td>
                  <td data-cell='Price' role='cell'>
                    {film.film_price}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </main>
  );
};
export default Catalogue;
