export const metadata = {
  title: "Thank You for Contacting Us",
  description: "Generated by create next app",
};
const ThankYou = () => {
  return (
    <main>
      <div>
        <h1>Thank you for your message!</h1>
        <p>We will get back to you shortly.</p>
      </div>
    </main>
  );
};
export default ThankYou;
