import Page from "./page"; // import your Demo's page

// Use to add metadata to 'use client' section

export const metadata = {
  title: "Search the Film Catalogue",
  description: "Generated by create next app",
};
export default Page;
